#!/usr/bin/env bash

ENV=$1

if [[ -z "$ENV" ]]; then
    echo "usage: $0 /etc/environment" >&2
    exit 1
fi

# Make sure that the file is writable
touch $ENV
if [[ $? -ne 0 ]]; then
    echo "$0: unable to modify ${ENV}" >&2
    exit 1
fi

sed -i -e '/^COREOS_PUBLIC_IPV4=/d' \
    -e '/^COREOS_PRIVATE_IPV4=/d' \
    "${ENV}"

here="$(cd $(dirname $0) && pwd)"
. $here/opennebula-common

if [ -z "$ETH0_IP" ] ; then
    exit 0
fi

echo "COREOS_PRIVATE_IPV4=$ETH0_IP" >> $ENV
if [ -n "$ETH1_IP" ] ; then
    echo "COREOS_PUBLIC_IPV4=$ETH1_IP" >> $ENV
else
    echo "COREOS_PUBLIC_IPV4=$ETH0_IP" >> $ENV
fi
